export const ROOT_ROUTE_KEY = 'ROOT';
export const LOGIN_ROUTE_KEY = 'LOGIN';
export const MEMBERSHIP_CARD_ROUTE_KEY = 'MEMBERSHIP_CARD_SCREEN';
export const ACCEPT_PRIVACY_POLICY_ROUTE_KEY = 'ACCEPT_PRIVACY_POLICY';
export const CREATE_PIN_ROUTE_KEY = 'CREATE_PIN';
export const CONFIRM_PIN_ROUTE_KEY = 'CONFIRM_PIN';
export const ENTER_PIN_ROUTE_KEY = 'ENTER_PIN';
export const NOTIFICATION_PERMISSIONS_ROUTE_KEY = 'NOTIFICATION_PERMISSIONS';
export const TAB_NAVIGATOR_ROUTE_KEY = 'TAB_NAVIGATOR';
export const MAP_ROUTE_KEY = 'MAP';
export const ONBOARDING_ROUTE_KEY = 'ONBOARDING';

// profile
export const PROFILE_STACK_ROUTE_KEY = 'PROFILE_STACK';
export const PROFILE_INDEX_ROUTE_KEY = 'PROFILE_INDEX';
export const PROFILE_MEMBER_EDIT_KEY = 'PROFILE_MEMBER_EDIT_KEY';
export const WALLET_ROUTE_KEY = 'WALLET';
// profile EDI section
export const PROFILE_MEMBERSHIP_CARD_ROUTE_KEY = 'PROFILE_MEMBERSHIP_CARD';
//
export const PROFILE_SUBSETTINGS_ROUTE_KEY = 'PROFILE_SUBSETTINGS';
export const PROFILE_SUBNOTIFICATIONS_ROUTE_KEY = 'PROFILE_SUBNOTIFICATIONS';
export const PROFILE_SUBSETTINGS_PRIVACY_POLICY_ROUTE_KEY =
  'PROFILE_SUBSETTINGS_PRIVACY_POLICY';
export const GET_HELP_ROUTE_KEY = 'GET_HELP';
export const PROFILE_SUBSETTINGS_SECURITY_ROUTE_KEY =
  'PROFILE_SUBSETTINGS_SECURITY';
export const PROFILE_SUBSETTINGS_ACCOUNT_INFORMATION_KEY =
  'PROFILE_SUBSETTINGS_ACCOUNT_INFORMATION_KEY';

// sharing
export const SHARING_STACK_ROUTE_KEY = 'SHARING_STACK';
export const SHARING_NAV_ROUTE_KEY = 'SHARING_NAV';

// portions
export const PORTION_LIST_ROUTE_KEY = 'PORTION_LIST';
export const PORTION_SEND_ROUTE_KEY = 'PORTION_SEND';

// chats
export const CHAT_LIST_ROUTE_KEY = 'CHAT_LIST';
export const COMPOSE_CHAT_ROUTE_KEY = 'COMPOSE_CHAT';
export const RECIPIENT_MEMBER_PROFILE_ROUTE_KEY = 'RECIPIENT_MEMBER_PROFILE';
export const ASSIGNMENT_DETAILS_ROUTE_KEY = 'ASSIGNMENT_DETAILS';

// bills navigators
export const BILL_STACK_ROUTE_KEY = 'BILL_STACK';
export const BILL_NAV_ROUTE_KEY = 'BILL_NAV';

// bill status lists
export const OPEN_BILL_LIST_ROUTE_KEY = 'OPEN_BILL_LIST';
export const CLOSED_BILL_LIST_ROUTE_KEY = 'CLOSED_BILL_LIST';

// bill
export const BILL_SCREEN_ROUTE_KEY = 'BILL_SCREEN';
export const BILL_DETAIL_SCREEN_ROUTE_KEY = 'BILL_DETAIL_SCREEN';
